export const mutations = {
    REGISTER_PERMISSION: 'REGISTER_PERMISSION',
    RESOLVE_PERMISSION: 'RESOLVE_PERMISSION'
};

export const actions = {
    REGISTER_PERMISSION: 'REGISTER_PERMISSION',
    RESOLVE_PERMISSIONS: 'RESOLVE_PERMISSIONS'
};

export const getters = {
    GET_PERMISSIONS: 'GET_PERMISSIONS',
    GET_PERMISSION: 'GET_PERMISSION'
};